services:
  - type: web
    name: chess
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn BlunderStruck.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: BlunderStruck.settings